defaults:
    - override hydra/launcher: submitit_local

# environment
task: dog-run
obs: state

# evaluation
checkpoint: ???
eval_episodes: 10
eval_freq: 50000

# training
steps: 10_000_000
batch_size: 256
reward_coef: 0.1
value_coef: 0.1
consistency_coef: 20
rho: 0.5
lr: 3e-4
enc_lr_scale: 0.3
grad_clip_norm: 20
tau: 0.01
discount_denom: 5
discount_min: 0.95
discount_max: 0.995
buffer_size: 1_000_000
exp_name: default
data_dir: ???

# planning
mpc: true
iterations: 6
num_samples: 512
num_elites: 64
num_pi_trajs: 24
horizon: 3
min_std: 0.05
max_std: 2
temperature: 0.5

# actor
log_std_min: -10
log_std_max: 2
entropy_coef: 1e-4

# critic
num_bins: 101
vmin: -10
vmax: +10

# architecture
model_size: ???
num_enc_layers: 2
enc_dim: 256
num_channels: 32
mlp_dim: 512
latent_dim: 512
task_dim: 96
num_q: 5
dropout: 0.01
simnorm_dim: 8

# logging
wandb_project: ???
wandb_entity: ???
wandb_silent: false
disable_wandb: true
save_csv: true

# misc
save_video: true
save_agent: true
seed: 1

# convenience
work_dir: ???
task_title: ???
multitask: ???
tasks: ???
obs_shape: ???
action_dim: ???
episode_length: ???
obs_shapes: ???
action_dims: ???
episode_lengths: ???
seed_steps: ???
bin_size: ???
sb3_algo: ppo       # for trajectory collection
morphology: false   # True if we want to use image + morphology observation
morphology_seed: 1  # Seed for morphology generation

# transform2act params
transform2act:
    env_name: ant
    agent_specs:
        batch_design: true
    # training parameters
    gamma: 0.995
    tau: 0.95
    policy_specs:
        name: v5
        htype: tanh
        skel_gnn_specs:
            layer_type: graph_conv
            hdims: [64, 64, 64]
            aggr: add
            bias: true
        skel_index_mlp:
            hdims: [128, 128]
            rescale_linear: true
        control_gnn_specs:
            layer_type: graph_conv
            hdims: [64, 64, 64]
            aggr: add
            bias: true
        control_index_mlp:
            hdims: [128, 128]
            rescale_linear: true
        attr_gnn_specs:
            layer_type: graph_conv
            hdims: [64, 64, 64]
            aggr: add
            bias: true
        attr_index_mlp:
            hdims: [128, 128]
            rescale_linear: true
        control_log_std: 0
        attr_log_std: -2.3
        fix_control_std: false
        fix_attr_std: false
    policy_optimizer: 'Adam'
    policy_lr: 5.e-5
    policy_momentum: 0.0
    policy_weightdecay: 0.0
    value_specs:
        htype: tanh
        design_flag_in_state: true
        onehot_design_flag: true
        mlp: [512, 256]
        gnn_specs:
            layer_type: graph_conv
            hdims: [64, 64, 64]
            aggr: add
            bias: true
    value_optimizer: 'Adam'
    value_lr: 3.e-4
    value_momentum: 0.0
    value_weightdecay: 0.0
    clip_epsilon: 0.2
    min_batch_size: 50000
    mini_batch_size: 2048
    num_optim_epoch: 10
    max_epoch_num: 1000
    seed: 1
    save_model_interval: 100


    robot_param_scale: 1
    skel_transform_nsteps: 5

    done_condition:
        max_ang: 60

    obs_specs:
        attr: ['depth']
        sim: []
        design: true
        clip_qvel: true
        use_projected_params: true
        use_body_ind: true
    max_body_depth: 4

    add_body_condition:
        max_nchild: 2

    robot:
        param_mapping: sin
        no_root_offset: true
        
        body_params:
            offset:
                type: 'xy'
                lb: [-0.5, -0.5]
                ub: [0.5, 0.5]

        joint_params: {}

        geom_params:
            size:
                lb: 0.03
                ub: 0.10
            ext_start:
                lb: 0.0
                ub: 0.2

        actuator_params:
            gear:
                lb: 20
                ub: 400